const initArray = [
	{ title: 'Текущий регион', region: 'ZZ' },
  { title: 'Австралия', region: 'AU' },
  { title: 'Австрия', region: 'AT' },
  { title: 'Азербайджан', region: 'AZ' },
  { title: 'Албания', region: 'AL' },
  { title: 'Алжир', region: 'DZ' },
  { title: 'Американское Самоа', region: 'AS' },
  { title: 'Ангилья', region: 'AI' },
  { title: 'Ангола', region: 'AO' },
  { title: 'Андорра', region: 'AD' },
  { title: 'Антигуа и Барбуда', region: 'AG' },
  { title: 'Аргентина', region: 'AR' },
  { title: 'Армения', region: 'AM' },
  { title: 'Афганистан', region: 'AF' },
  { title: 'Багамы', region: 'BS' },
  { title: 'Бангладеш', region: 'BD' },
  { title: 'Бахрейн', region: 'BH' },
  { title: 'Беларусь', region: 'BY' },
  { title: 'Белиз', region: 'BZ' },
  { title: 'Бельгия', region: 'BE' },
  { title: 'Бенин', region: 'BJ' },
  { title: 'Болгария', region: 'BG' },
  { title: 'Боливия', region: 'BO' },
  { title: 'Босния и Герцеговина', region: 'BA' },
  { title: 'Ботсвана', region: 'BW' },
  { title: 'Бразилия', region: 'BR' },
  { title: 'Бруней-Даруссалам', region: 'BN' },
  { title: 'Буркина-Фасо', region: 'BF' },
  { title: 'Бурунди', region: 'BI' },
  { title: 'Бутан', region: 'BT' },
  { title: 'Вануату', region: 'VU' },
  { title: 'Великобритания', region: 'GB' },
  { title: 'Венгрия', region: 'HU' },
  { title: 'Венесуэла', region: 'VE' },
  { title: 'Виргинские о-ва (Британские)', region: 'VG' },
  { title: 'Виргинские о-ва (США)', region: 'VI' },
  { title: 'Восточный Тимор', region: 'TL' },
  { title: 'Вьетнам', region: 'VN' },
  { title: 'Габон', region: 'GA' },
  { title: 'Гаити', region: 'HT' },
  { title: 'Гайана', region: 'GY' },
  { title: 'Гамбия', region: 'GM' },
  { title: 'Гана', region: 'GH' },
  { title: 'Гваделупа', region: 'GP' },
  { title: 'Гватемала', region: 'GT' },
  { title: 'Германия', region: 'DE' },
  { title: 'Гернси', region: 'GG' },
  { title: 'Гибралтар', region: 'GI' },
  { title: 'Гондурас', region: 'HN' },
  { title: 'Гонконг', region: 'HK' },
  { title: 'Гренландия', region: 'GL' },
  { title: 'Греция', region: 'GR' },
  { title: 'Грузия', region: 'GE' },
  { title: 'Дания', region: 'DK' },
  { title: 'Джерси', region: 'JE' },
  { title: 'Джибути', region: 'DJ' },
  { title: 'Доминика', region: 'DM' },
  { title: 'Доминиканская Республика', region: 'DO' },
  { title: 'Египет', region: 'EG' },
  { title: 'Замбия', region: 'ZM' },
  { title: 'Зимбабве', region: 'ZW' },
  { title: 'Израиль', region: 'IL' },
  { title: 'Индия', region: 'IN' },
  { title: 'Индонезия', region: 'ID' },
  { title: 'Иордания', region: 'JO' },
  { title: 'Ирак', region: 'IQ' },
  { title: 'Ирландия', region: 'IE' },
  { title: 'Исландия', region: 'IS' },
  { title: 'Испания', region: 'ES' },
  { title: 'Италия', region: 'IT' },
  { title: 'Кабо-Верде', region: 'CV' },
  { title: 'Казахстан', region: 'KZ' },
  { title: 'Камбоджа', region: 'KH' },
  { title: 'Камерун', region: 'CM' },
  { title: 'Канада', region: 'CA' },
  { title: 'Катар', region: 'QA' },
  { title: 'Кения', region: 'KE' },
  { title: 'Кипр', region: 'CY' },
  { title: 'Киргизия', region: 'KG' },
  { title: 'Кирибати', region: 'KI' },
  { title: 'Колумбия', region: 'CO' },
  { title: 'Конго - Браззавиль', region: 'CG' },
  { title: 'Конго - Киншаса', region: 'CD' },
  { title: 'Коста-Рика', region: 'CR' },
  { title: 'Кот-д’Ивуар', region: 'CI' },
  { title: 'Куба', region: 'CU' },
  { title: 'Кувейт', region: 'KW' },
  { title: 'Лаос', region: 'LA' },
  { title: 'Латвия', region: 'LV' },
  { title: 'Лесото', region: 'LS' },
  { title: 'Ливан', region: 'LB' },
  { title: 'Ливия', region: 'LY' },
  { title: 'Литва', region: 'LT' },
  { title: 'Лихтенштейн', region: 'LI' },
  { title: 'Люксембург', region: 'LU' },
  { title: 'Маврикий', region: 'MU' },
  { title: 'Мадагаскар', region: 'MG' },
  { title: 'Македония (БЮРМ)', region: 'MK' },
  { title: 'Малави', region: 'MW' },
  { title: 'Малайзия', region: 'MY' },
	{ title: 'Мали', region: 'ML' },
  { title: 'Мальдивы', region: 'MV' },
  { title: 'Мальта', region: 'MT' },
  { title: 'Марокко', region: 'MA' },
  { title: 'Мексика', region: 'MX' },
  { title: 'Мозамбик', region: 'MZ' },
  { title: 'Молдова', region: 'MD' },
  { title: 'Монголия', region: 'MN' },
  { title: 'Монтсеррат', region: 'MS' },
  { title: 'Мьянма (Бирма)', region: 'MM' },
  { title: 'Намибия', region: 'NA' },
  { title: 'Науру', region: 'NR' },
  { title: 'Непал', region: 'NP' },
  { title: 'Нигер', region: 'NE' },
  { title: 'Нигерия', region: 'NG' },
  { title: 'Нидерланды', region: 'NL' },
  { title: 'Никарагуа', region: 'NI' },
  { title: 'Ниуэ', region: 'NU' },
  { title: 'Новая Зеландия', region: 'NZ' },
  { title: 'Норвегия', region: 'NO' },
  { title: 'о-в Мэн', region: 'IM' },
  { title: 'о-в Норфолк', region: 'NF' },
  { title: 'о-в Св. Елены', region: 'SH' },
  { title: 'о-ва Питкэрн', region: 'PN' },
  { title: 'ОАЭ', region: 'AE' },
  { title: 'Оман', region: 'OM' },
  { title: 'Острова Кука', region: 'CK' },
  { title: 'Пакистан', region: 'PK' },
  { title: 'Палестина', region: 'PS' },
  { title: 'Панама', region: 'PA' },
  { title: 'Папуа — Новая Гвинея', region: 'PG' },
  { title: 'Парагвай', region: 'PY' },
  { title: 'Перу', region: 'PE' },
  { title: 'Польша', region: 'PL' },
  { title: 'Португалия', region: 'PT' },
  { title: 'Пуэрто-Рико', region: 'PR' },
  { title: 'Республика Корея', region: 'KR' },
  { title: 'Россия', region: 'RU' },
  { title: 'Руанда', region: 'RW' },
  { title: 'Румыния', region: 'RO' },
  { title: 'Сальвадор', region: 'SV' },
  { title: 'Самоа', region: 'WS' },
  { title: 'Сан-Марино', region: 'SM' },
  { title: 'Сан-Томе и Принсипи', region: 'ST' },
  { title: 'Саудовская Аравия', region: 'SA' },
  { title: 'Сейшельские Острова', region: 'SC' },
  { title: 'Сенегал', region: 'SN' },
  { title: 'Сент-Винсент и Гренадины', region: 'VC' },
  { title: 'Сербия', region: 'RS' },
  { title: 'Сингапур', region: 'SG' },
  { title: 'Словакия', region: 'SK' },
  { title: 'Словения', region: 'SI' },
  { title: 'Соединенные Штаты', region: 'US' },
  { title: 'Соломоновы Острова', region: 'SB' },
  { title: 'Сомали', region: 'SO' },
  { title: 'Суринам', region: 'SR' },
  { title: 'Сьерра-Леоне', region: 'SL' },
  { title: 'Таджикистан', region: 'TJ' },
  { title: 'Таиланд', region: 'TH' },
  { title: 'Тайвань', region: 'TW' },
  { title: 'Танзания', region: 'TZ' },
  { title: 'Того', region: 'TG' },
  { title: 'Токелау', region: 'TK' },
  { title: 'Тонга', region: 'TO' },
  { title: 'Тринидад и Тобаго', region: 'TT' },
  { title: 'Тунис', region: 'TN' },
  { title: 'Туркменистан', region: 'TM' },
  { title: 'Турция', region: 'TR' },
  { title: 'Уганда', region: 'UG' },
  { title: 'Узбекистан', region: 'UZ' },
  { title: 'Украина', region: 'UA' },
  { title: 'Уругвай', region: 'UY' },
  { title: 'Федеративные Штаты Микронезии', region: 'FM' },
  { title: 'Фиджи', region: 'FJ' },
  { title: 'Филиппины', region: 'PH' },
  { title: 'Финляндия', region: 'FI' },
  { title: 'Франция', region: 'FR' },
  { title: 'Хорватия', region: 'HR' },
  { title: 'Центрально-Африканская Республика', region: 'CF' },
  { title: 'Чад', region: 'TD' },
  { title: 'Черногория', region: 'ME' },
  { title: 'Чехия', region: 'CZ' },
  { title: 'Чили', region: 'CL' },
  { title: 'Швейцария', region: 'CH' },
  { title: 'Швеция', region: 'SE' },
  { title: 'Шри-Ланка', region: 'LK' },
  { title: 'Эквадор', region: 'EC' },
  { title: 'Эстония', region: 'EE' },
  { title: 'Эфиопия', region: 'ET' },
  { title: 'Южно-Африканская Республика', region: 'ZA' },
  { title: 'Ямайка', region: 'JM' },
	{ title: 'Япония', region: 'JP' } 
];